#!/bin/sh

# Mount essential filesystems
mount -t proc proc /proc
mount -t sysfs sysfs /sys
mount -t devtmpfs devtmpfs /dev

# Create device nodes if they don't exist
[ ! -c /dev/console ] && mknod /dev/console c 5 1
[ ! -c /dev/null ] && mknod /dev/null c 1 3

echo "Welcome to the guest Linux system!"
echo "BusyBox init system started."

echo "All tests passed!"

poweroff -f

# # Start a shell
# exec /bin/sh

